language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ./Natours/starter/node_modules


before_install:
  - cd ./Natours/starter
install:
  - npm ci


# before_script:
script:
  - npm run compile-sass


before_deploy:
  - rm -rf ./.gitignore
  - rm -rf ./node_modules
  - rm -rf ./package*
  - rm -rf ./sass
deploy:
  provider: pages
  local_dir: ./Natours/starter
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository
  keep_history: false
  on:
    branch: master